---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: 12.21.26

verifier:
  name: inspec

provisioner:
  name: chef_zero
  data_path: 'test/integration'
  data_bags_path: 'test/integration/data_bags/'
  environments_path: 'test/integration/environments'
  cookbooks_path: '../'
#  encrypted_data_bag_secret_key_path: 'test/integration/data_bags/test_key'
  client_rb:
    treat_deprecation_warnings_as_errors: true
    resource_cloning: false
    environment: staging

platforms:
  - name: debian-9
    driver_config:
      image: debian:stretch-slim
      platform: debian
      publish_all: false
      privileged: false
      provision_command: apt-get update


suites:
  - name: d-ber1-testkitchen-001
    driver:
      hostname: d-ber1-testkitchen-001
    run_list:
      - recipe[cookbook_attributes_per_host::default]

  - name: d-ber1-testkitchen-002
    driver:
      hostname: d-ber1-testkitchen-002
    run_list:
      - recipe[cookbook_attributes_per_host::default]

  - name: d-ber1-testkitchen-003
    driver:
      hostname: d-ber1-testkitchen-003
    run_list:
      - recipe[cookbook_attributes_per_host::default]
